/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = [".accordion[_ngcontent-%COMP%] {\r\n    background-color: #eee;\r\n    color: rgb(27, 36, 218);\r\n    cursor: pointer;\r\n    padding: 18px;\r\n    width: 100%;\r\n    border: none;\r\n    text-align: left;\r\n    outline: none;\r\n    font-size: 15px;\r\n}\r\n\r\n.active[_ngcontent-%COMP%], .accordion[_ngcontent-%COMP%]:hover {\r\n    background-color: #ccc; \r\n}\r\n\r\n.panel[_ngcontent-%COMP%] {\r\n    padding: 0 18px;\r\n    background-color: white;\r\n    overflow: hidden;\r\n}"];
export { styles as styles };
//# sourceMappingURL=collapse.component.css.shim.ngstyle.js.map